export const contentItems = [
  {
    id: 'hybrid-work-guide', title: 'Hybrid work and office attendance guide', type: 'Policy',
    summary: 'How to plan team days, work across locations, and find office-specific resources.',
    body: 'PURPOSE\nUse this guide to coordinate in-person collaboration with focused work across locations. Employees should keep their work location and availability current in the team calendar and follow the arrangements agreed with their manager.\n\nPLAN A TEAM DAY\nChoose dates that support work best done together, such as planning, onboarding, or workshops. Share the date and office location early. Reserve a workspace or meeting room when required, and include remote colleagues in the agenda and discussion.\n\nWORKING ONSITE\nUse the current office directory for building hours, access instructions, room details, and local contacts. Keep shared spaces tidy, use headsets for calls, and leave meeting rooms ready for the next group.\n\nCHANGES AND SUPPORT\nTell your manager when a schedule change affects a team commitment. Contact Workplace Services for location questions and People Operations for individual work-arrangement support.',
    audience: 'All employees', owner: 'People Operations', status: 'published', updatedAt: '2026-09-28', reviewDate: '2026-12-15',
  },
  {
    id: 'information-handling', title: 'Secure collaboration and information handling', type: 'Policy',
    summary: 'Practical steps for sharing information safely in meetings, messages, and shared workspaces.',
    body: 'BEFORE YOU SHARE\nConfirm that each recipient needs the information and that the audience matches the document’s sensitivity. Check names and addresses before sending, use an approved collaboration space, and grant the minimum access needed.\n\nWORKING IN SHARED SPACES\nPosition screens away from public view, lock devices when you step away, and collect printed pages promptly. Do not leave restricted material in meeting rooms or shared printers.\n\nUSING LINKS AND ATTACHMENTS\nPrefer a managed link with access controls over a downloaded copy. Review sharing settings when a project or working group ends. Do not move company information to personal email, personal storage, or an unapproved application.\n\nWHEN SOMETHING LOOKS WRONG\nPause before opening unexpected attachments or entering credentials. Report suspected misdelivery or exposure through the security incident channel. Contact Information Security if a collaboration need does not fit the approved tools.',
    audience: 'All employees', owner: 'Information Security', status: 'published', updatedAt: '2026-09-25', reviewDate: '2026-12-15',
  },
  {
    id: 'manager-faq', title: 'Hybrid work: manager questions and answers', type: 'FAQ',
    summary: 'Answers for managers coordinating schedules, team days, and individual work arrangements.',
    body: 'How should I set team-day expectations?\nAgree on the purpose, cadence, and notice period with the team. Publish the plan in the shared calendar and make sure remote colleagues can participate. Review the arrangement when team needs change.\n\nWhat if an employee cannot attend on a planned day?\nDiscuss the situation privately, confirm any time-sensitive work, and agree on a practical alternative. Avoid sharing personal details with the wider team. Refer individual arrangement questions to People Operations.\n\nHow do I plan an inclusive meeting?\nShare the agenda in advance, use accessible rooms and collaboration tools, and make decisions visible to everyone afterward.\n\nWhere can I find location details?\nUse the office directory for building access, room booking, and local Workplace Services contacts.',
    audience: 'People managers', owner: 'People Operations', status: 'published', updatedAt: '2026-09-29', reviewDate: '2026-12-01',
  },
  {
    id: 'october-newsletter', title: 'October employee update: events, resources, and team news', type: 'Newsletter',
    summary: 'A monthly roundup of learning sessions, workplace updates, and useful employee resources.',
    body: 'OCTOBER AT A GLANCE\nThis month’s employee update brings together upcoming learning sessions, workplace reminders, and resources teams have asked for. Add the events that matter to your calendar and share relevant links with your group.\n\nLEARNING\nThe October learning calendar includes short sessions on giving useful feedback, managing project handoffs, and working securely with shared files. Registration details are available in the learning portal.\n\nWORKPLACE\nCheck the office directory before visiting a different location. It includes current access instructions, room guidance, and local service contacts.\n\nPEOPLE RESOURCES\nThe benefits and wellbeing pages have been refreshed for the upcoming planning season. Review the current information in the employee portal and contact People Operations with individual questions.\n\nSTAY CONNECTED\nSend team announcements and event updates to Employee Communications with an owner, audience, and publish date.',
    audience: 'All employees', owner: 'Employee Communications', status: 'published', updatedAt: '2026-09-30', reviewDate: '2026-10-15',
  },
  {
    id: 'onboarding-ideas', title: 'New-starter community: October discussion and resources', type: 'Community update',
    summary: 'Upcoming peer sessions and practical resources for employees in their first months.',
    body: 'OCTOBER DISCUSSION\nThe new-starter community will meet this month to compare onboarding tips, ask questions about common tools, and meet colleagues from other teams. New employees and onboarding buddies are welcome.\n\nPEER SESSIONS\n• Week one: finding the right people and internal resources\n• Week two: planning a productive first one-to-one\n• Week three: organizing work across teams and locations\n\nGET READY\nBring one question you had during your first month and one resource that helped you. Do not share confidential project or employee information in the group.\n\nJOIN THE COMMUNITY\nUse the community directory to find the next session, review discussion notes, and volunteer as a peer buddy.',
    audience: 'New employees', owner: 'Community Programs', status: 'published', updatedAt: '2026-09-26', reviewDate: '2026-10-31',
  },
  {
    id: 'leadership-update', title: 'Quarterly priorities: service, clarity, and collaboration', type: 'Announcement',
    summary: 'A leadership update on improving employee service, communication, and cross-team work.',
    body: 'A NOTE FROM LEADERSHIP\nAs we begin the new quarter, our focus is on making everyday work easier to navigate. Teams are reviewing how they share decisions, hand off work, and keep employee resources current.\n\nOUR PRIORITIES\n• Improve the clarity of team goals and ownership.\n• Reduce avoidable friction in common employee processes.\n• Share decisions and changes in a place people can find later.\n• Build stronger connections across teams and locations.\n\nWHAT THIS MEANS FOR TEAMS\nManagers will discuss the priorities in team meetings and identify one practical improvement to test. Share questions with your manager or submit feedback through the employee experience channel. Updates and progress notes will be posted throughout the quarter.',
    audience: 'All employees', owner: 'Executive Communications', status: 'published', updatedAt: '2026-09-24', reviewDate: '2026-10-31',
  },
  {
    id: 'records-quick-guide', title: 'Records management: retention and disposition', type: 'Policy',
    summary: 'How to find the right records schedule, preserve business records, and request help.',
    body: 'START WITH THE SCHEDULE\nUse the current records schedule for your business area to determine how long a record must be retained and how it should be disposed of. The schedule in the records portal is the source of truth; do not rely on a local copy.\n\nPRESERVE THE BUSINESS RECORD\nKeep final decisions, approvals, and supporting records in the approved system for the work. Use clear names and include enough context for a colleague to understand the record later.\n\nBEFORE YOU DELETE OR MOVE\nCheck for a retention requirement, active review, investigation, or preservation notice. If you are unsure, stop and contact your Records Manager. Do not delete material covered by a preservation notice.\n\nGET HELP\nThe Records Management team can help identify the right schedule and approved storage location.',
    audience: 'All employees', owner: 'Records Management', status: 'published', updatedAt: '2026-09-21', reviewDate: '2027-01-15',
  },
  {
    id: 'onboarding-checklist', title: 'New employee onboarding: first 30 days', type: 'Checklist',
    summary: 'A practical first-month checklist for new employees, managers, and onboarding buddies.',
    body: 'BEFORE THE FIRST DAY\nConfirm that equipment, account access, building information, and the first-week schedule are ready. The manager should share a short welcome note and identify an onboarding buddy.\n\nWEEK ONE\n• Meet the manager and immediate team.\n• Review the team charter, current priorities, and communication norms.\n• Set up required tools and complete assigned security and workplace learning.\n• Find the employee directory, help channels, and People Operations resources.\n\nWEEKS TWO THROUGH FOUR\nSchedule introductions with close partners, review role expectations, and agree on a first-month goal. The manager and employee should hold a check-in at the end of each week.\n\nAT DAY 30\nDiscuss what is clear, what remains difficult to find, and which relationships or training would help next. Record agreed actions in the employee’s development notes.',
    audience: 'New employees', owner: 'People Operations', status: 'published', updatedAt: '2026-09-30', reviewDate: '2026-12-01',
  },
  {
    id: 'benefits-enrollment-guide', title: 'Benefits planning and enrollment guide', type: 'Guide',
    summary: 'Where to compare benefit options, prepare for enrollment, and get personal support.',
    body: 'PREPARE TO ENROLL\nReview the current plan summaries and enrollment dates in the benefits portal. Compare coverage, payroll contributions, provider networks, and available support before making a selection. The portal displays the options available to you.\n\nBEFORE YOU SUBMIT\nCheck dependent details, confirm each selection, and save the confirmation page for your records. If you are not making changes, review whether you still need to confirm your current selections.\n\nLIFE CHANGES\nCertain life events may require an update outside the annual enrollment period. Review the current plan rules and submission windows in the portal as soon as possible after a change.\n\nGET HELP\nUse the benefits help center for plan comparisons and contact the Benefits team for questions about your individual situation. Do not post personal health or dependent information in a public channel.',
    audience: 'All employees', owner: 'Benefits Team', status: 'published', updatedAt: '2026-09-30', reviewDate: '2026-10-15',
  },
  {
    id: 'leave-and-workplace-support', title: 'Time away and workplace support: where to start', type: 'FAQ',
    summary: 'How to find leave information, request workplace support, and protect personal details.',
    body: 'Where can I review time-away options?\nStart in the People portal for current leave types, eligibility information, and request steps. The portal contains the latest guidance for your location and circumstances.\n\nHow do I ask for a workplace adjustment?\nContact People Operations through the confidential support channel. A specialist will explain the process and what information is needed. Share health or personal details only through the approved private channel.\n\nShould I tell my whole team?\nShare only the schedule or coverage details colleagues need to plan work. Managers should keep personal information private and coordinate coverage with the employee.\n\nWho can help with a question about eligibility?\nPeople Operations can explain the current process and direct you to the right specialist. Do not rely on an old email or a colleague’s individual experience as the current rule.',
    audience: 'All employees', owner: 'People Operations', status: 'published', updatedAt: '2026-09-29', reviewDate: '2026-12-15',
  },
  {
    id: 'expense-reimbursement-guide', title: 'Business expenses: submission and reimbursement', type: 'Guide',
    summary: 'Steps for documenting approved business expenses and resolving a reimbursement issue.',
    body: 'BEFORE YOU SPEND\nConfirm that the expense supports a business need and has the approval required by your team. Use the preferred booking or purchasing channel when one is available. Ask your manager before committing to an expense that is outside the normal plan.\n\nSUBMIT A CLAIM\nEnter the business purpose, date, category, and cost in the expense system. Attach an itemized receipt and add context for charges that may not be clear from the receipt alone. Submit promptly so the approver can review it while details are fresh.\n\nAFTER SUBMISSION\nCheck the status in the expense system. Respond to requests for more information there rather than creating a duplicate claim.\n\nNEED HELP?\nUse the Finance help channel for a returned claim, missing receipt, or system issue. Never include payment card details in a support message.',
    audience: 'All employees', owner: 'Finance Operations', status: 'published', updatedAt: '2026-09-27', reviewDate: '2026-11-15',
  },
  {
    id: 'technology-access-guide', title: 'Technology access and equipment requests', type: 'Guide',
    summary: 'How to request application access, prepare a device, and get help with common issues.',
    body: 'REQUEST ACCESS\nOpen the service portal and choose the application or access group you need. Include your role, manager, business reason, and project or team details. Your manager or system owner may need to approve the request.\n\nSET UP A DEVICE\nFollow the device setup steps from IT, install only approved software, and use your managed account for company work. Keep operating systems and security tools current.\n\nTROUBLESHOOT\nRestart the device, check the service-status page, and search the IT knowledge base before opening a ticket. Include the device type, application, approximate time, and any error message. Do not send passwords or authentication codes.\n\nRETURN OR REPLACE EQUIPMENT\nContact IT before moving, replacing, or returning a managed device so the team can protect data and update the asset record.',
    audience: 'All employees', owner: 'IT Service Desk', status: 'published', updatedAt: '2026-09-26', reviewDate: '2026-12-01',
  },
  {
    id: 'security-incident-response', title: 'Report a security concern or suspicious message', type: 'Policy',
    summary: 'Quick actions for suspected phishing, lost devices, accidental sharing, or unusual account activity.',
    body: 'IF YOU RECEIVE A SUSPICIOUS MESSAGE\nDo not open unexpected attachments, follow login links, or reply with credentials. Use the mail client’s report function or forward the message to the security reporting channel. Include the original message when possible.\n\nIF YOU CLICKED OR SHARED SOMETHING\nReport it promptly, even if you are unsure whether information was exposed. Include what happened, when it happened, and the affected account, device, or file. Do not delete evidence or try to investigate on your own.\n\nLOST DEVICE OR UNUSUAL SIGN-IN\nContact the IT Service Desk and Information Security immediately. Follow their instructions to secure the account and device.\n\nWHAT HAPPENS NEXT\nThe response team will assess the report, give you any actions to take, and share updates through the approved channel. Early reporting helps limit impact.',
    audience: 'All employees', owner: 'Information Security', status: 'published', updatedAt: '2026-09-30', reviewDate: '2026-12-01',
  },
  {
    id: 'business-travel-guide', title: 'Business travel planning and support', type: 'Guide',
    summary: 'Plan approved travel, prepare for a productive trip, and find support while away.',
    body: 'BEFORE BOOKING\nConfirm the business purpose, budget, and approval with your manager. Use the current travel booking channel and review the travel guidance for your destination. Add the itinerary to your work calendar so colleagues know when you are available.\n\nBEFORE DEPARTURE\nCheck transport and meeting details, confirm how to access work systems securely, and save the Travel Support contact. Take only the equipment you need and keep devices with you.\n\nWHILE TRAVELING\nUse approved networks and collaboration tools. Avoid discussing sensitive work where others can overhear. Contact Travel Support if plans change or you need help.\n\nAFTER THE TRIP\nSubmit eligible expenses through the expense system and include receipts and business purpose. Share useful trip notes with the team and close out temporary access or bookings.',
    audience: 'Frequent travelers', owner: 'Workplace Services', status: 'published', updatedAt: '2026-09-25', reviewDate: '2026-12-01',
  },
  {
    id: 'learning-and-development', title: 'Learning and development: plan your next step', type: 'Guide',
    summary: 'Find role-based learning, set a development goal, and discuss progress with your manager.',
    body: 'FIND LEARNING\nBrowse the learning portal by role, skill, format, and time commitment. Start with required learning, then choose a resource that supports a current project or development goal.\n\nMAKE A PLAN\nChoose one skill to build, identify a practical way to apply it, and set a check-in date. Learning can include a course, peer shadowing, a stretch assignment, or a community of practice.\n\nDISCUSS WITH YOUR MANAGER\nBring the goal to a one-to-one. Agree how the work fits with team priorities and what support would help. Record the action in your development plan.\n\nSHARE WHAT WORKS\nRecommend useful resources in the learning community. Include the audience, time required, and a short note about when the resource is most useful.',
    audience: 'All employees', owner: 'Learning and Development', status: 'published', updatedAt: '2026-09-24', reviewDate: '2027-01-15',
  },
  {
    id: 'manager-one-on-one-guide', title: 'Manager one-to-ones: a practical conversation guide', type: 'Checklist',
    summary: 'A simple structure for regular check-ins about priorities, feedback, and employee support.',
    body: 'BEFORE THE MEETING\nShare a short agenda and ask the employee to add topics. Review open actions from the last conversation and leave space for items that are not on the list.\n\nDURING THE CHECK-IN\n• Ask what is going well and where work is blocked.\n• Review near-term priorities and resolve competing deadlines.\n• Give specific, timely feedback and invite the employee’s view.\n• Discuss learning, workload, and support needs.\n\nAFTER THE MEETING\nSummarize decisions and owners in a private note. Share only the actions needed by other colleagues. Follow up on commitments before the next meeting.\n\nKEEP IT USEFUL\nA one-to-one is a conversation, not a status report. Adjust the format to the employee’s needs and raise confidential concerns through the appropriate People Operations channel.',
    audience: 'People managers', owner: 'People Operations', status: 'published', updatedAt: '2026-09-23', reviewDate: '2027-01-15',
  },
  {
    id: 'office-access-and-visitors', title: 'Office access, visitors, and meeting rooms', type: 'FAQ',
    summary: 'Everyday guidance for building access, hosting a visitor, and using shared spaces.',
    body: 'How do I check building hours and access?\nUse the office directory for current location details, building hours, entry instructions, and Workplace Services contacts. Contact the local team before traveling if your access needs have changed.\n\nHow do I host a visitor?\nRegister the visitor through the approved reception process, share arrival instructions, and meet them at the designated point. Visitors must follow the host’s instructions while onsite.\n\nHow should I use meeting rooms?\nReserve the room for the time needed, include remote participants, and release the booking if plans change. End on time, remove personal items, and leave the room ready for the next meeting.\n\nWhat if my badge does not work?\nContact building support or Workplace Services using the local office contact list. Do not lend your badge or hold a secured door for an unknown visitor.',
    audience: 'Office employees', owner: 'Workplace Services', status: 'published', updatedAt: '2026-09-22', reviewDate: '2026-11-15',
  },
  {
    id: 'internal-opportunities', title: 'Explore internal roles and project opportunities', type: 'Guide',
    summary: 'Where to find internal openings, prepare for a conversation, and discuss a development move.',
    body: 'EXPLORE OPTIONS\nReview current internal roles and short-term project opportunities in the careers portal. Save roles that match your interests and compare the responsibilities, skills, and location expectations.\n\nTALK WITH YOUR MANAGER\nShare your development goals and ask about projects that could build relevant experience. A career conversation does not require an immediate move; it can help shape your next learning step.\n\nAPPLY FOR A ROLE\nFollow the instructions in the careers portal, update your resume or internal profile, and prepare examples that show the skills required. Contact the recruiting team if you need help understanding the process.\n\nKEEP INFORMATION PRIVATE\nUse the careers portal for application details and share plans only with people who need to know. The recruiting team can explain confidentiality and timing questions.',
    audience: 'All employees', owner: 'Talent Acquisition', status: 'published', updatedAt: '2026-09-20', reviewDate: '2027-01-31',
  },
  {
    id: 'wellbeing-resources', title: 'Wellbeing resources and support options', type: 'Guide',
    summary: 'A starting point for finding wellbeing programs, confidential support, and everyday resources.',
    body: 'START IN THE PEOPLE PORTAL\nThe People portal lists current wellbeing programs, confidential support options, and resources for different locations. Review the provider details and eligibility information before using a service.\n\nFIND THE RIGHT SUPPORT\nFor a workplace question, contact People Operations. For a benefits or coverage question, use the Benefits help center. For an urgent safety concern, use the emergency contact details for your location.\n\nPROTECT YOUR PRIVACY\nUse the designated private channel when a question involves personal or health information. Share only the details needed to receive support. Managers should avoid collecting personal information in team documents or public channels.\n\nKEEP RESOURCES CURRENT\nCheck the People portal for provider changes and current contact information rather than relying on an old message or printed copy.',
    audience: 'All employees', owner: 'People Operations', status: 'published', updatedAt: '2026-09-19', reviewDate: '2027-01-31',
  },
]
